language: lua

before_install:
  - sudo apt-get update
  # libssl-dev is used to build luasec
  # git is used to install luabitop
  - sudo apt-get install -y luarocks libssl-dev git
  - lua -v
  - sudo luarocks install luabitop
  - sudo luarocks install busted
  # luasec depends on luasocket but it's breaking luarocks on trusty, so it should be placed last
  - sudo luarocks install luasec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu

script: busted -e 'package.path="./?/init.lua;./?.lua;"..package.path' tests/spec/*.lua

# testing installing from luarocks
after_script:
  - sudo luarocks install luamqtt
  - busted tests/spec/*.lua
